import numpy as np

m12_bins_displaced_1 = np.linspace(0., 10., 10 + 1)    
m12_bins_displaced_2 = np.array([0., 1., 2., 3., 4., 5., 10]) 
m12_bins_displaced_3 = np.array([0., 1., 2., 3., 10])     

# m12_bins_displaced_1_alt = np.array([0., 1., 2., 3., 4., 5., 6., 8., 10.])    
# m12_bins_displaced_2_alt = np.array([0., 1., 2., 3., 4., 10]) 
# m12_bins_displaced_3_alt = np.array([0., 1., 2., 3., 10])     

m12_bins_displaced_1_alt = np.array([0., 1., 2., 3., 4., 10., 20.])    
m12_bins_displaced_2_alt = np.array([0., 1., 2., 3., 4., 10., 20.]) 
m12_bins_displaced_3_alt = np.array([0., 1., 2., 3., 10., 20.])     

m12_bins_displaced_1_coarse = np.linspace(0., 10., 5 + 1)    
m12_bins_displaced_2_coarse = np.array([0., 2., 4., 10, 20.]) 
m12_bins_displaced_3_coarse = np.array([0., 2., 4., 10, 20.])     
    
m12_bins_martina = np.array([0., 4., 10., 20.]) 
m12_bins_martina_wide = np.array([0., 4., 20.]) 


branches = [
    ('run'                          , '_runNb'               ),
    ('lumi'                         , '_lumiBlock'           ),
    ('event'                        , '_eventNb'             ),
    ('bx'                           , None                   ),
    ('orbit_number'                 , None                   ),
    ('is_data'                      , None                   ),
    ('n_pu'                         , None                   ),
    ('rho'                          , None                   ),
    ('n_vtx'                        , None                   ),
    ('weight'                       , None                   ),
    ('puweight'                     , 'w_pileupSF'           , np.linspace(0.,4.,12 + 1)    ),
    ('n_cands'                      , None                   ),
    ('hnl_w_pt'                     , None                   ),
    ('hnl_w_px'                     , None                   ),
    ('hnl_w_py'                     , None                   ),
    ('hnl_w_pz'                     , None                   ),
    ('hnl_w_e'                      , None                   ),
    ('hnl_w_eta'                    , None                   ),
    ('hnl_w_phi'                    , None                   ),
    ('hnl_w_q'                      , None                   ),
    ('hnl_w_m'                      , None                   ),
    ('hnl_w_sum_pt'                 , None                   ),
    ('hnl_w_vis_pt'                 , None                   ),
    ('hnl_w_vis_eta'                , None                   ),
    ('hnl_w_vis_phi'                , None                   ),
    ('hnl_w_vis_q'                  , None                   ),
    ('hnl_w_vis_m'                  , 'Mlll'                 , np.linspace(0.,200.,20 + 1)    ),
    ('hnl_w_vis_sum_pt'             , None                   ),
    ('hnl_hn_pt'                    , None                   ),
    ('hnl_hn_px'                    , None                   ),
    ('hnl_hn_py'                    , None                   ),
    ('hnl_hn_pz'                    , None                   ),
    ('hnl_hn_e'                     , None                   ),
    ('hnl_hn_eta'                   , None                   ),
    ('hnl_hn_phi'                   , None                   ),
    ('hnl_hn_q'                     , None                   ),
    ('hnl_hn_m'                     , None                   ),
    ('hnl_hn_sum_pt'                , None                   ),
    ('hnl_hn_vis_pt'                , None                   ),
    ('hnl_hn_vis_eta'               , None                   ),
    ('hnl_hn_vis_phi'               , None                   ),
    ('hnl_hn_vis_q'                 , None                   ),
    ('hnl_hn_vis_m'                 , None                   ),
    ('hnl_hn_vis_sum_pt'            , None                   ),
    ('hnl_m_01'                     , None                   ),
    ('hnl_m_02'                     , None                   ),
    ('hnl_m_12'                     , 'Ml2l3'                , np.array([0., 4., 20.])),
    ('hnl_q_01'                     , None                   ),
    ('hnl_q_02'                     , None                   ),
    ('hnl_q_12'                     , None                   ),
    ('hnl_dr_01'                    , 'deltaRl1l2'           , np.linspace( 0., 6.3 , 12 + 1)    ),
    ('hnl_dr_02'                    , 'deltaRl1l3'           , np.linspace( 0., 6.3 , 12 + 1)    ),
    ('hnl_dr_12'                    , 'deltaRl2l3'           , np.linspace( 0., 6.3 , 12 + 1)    ),
    ('hnl_dphi_01'                  , 'deltaFl1l2'           , np.linspace( 0., 3.15, 12 + 1)    ),
    ('hnl_dphi_02'                  , 'deltaFl1l3'           , np.linspace( 0., 3.15, 12 + 1)    ),
    ('hnl_dphi_12'                  , 'deltaFl2l3'           , np.linspace( 0., 3.15, 12 + 1)    ),
    ('hnl_dr_0met'                  , None                   ),
    ('hnl_dr_1met'                  , None                   ),
    ('hnl_dr_2met'                  , None                   ),
    ('hnl_dphi_0met'                , None                   ),
    ('hnl_dphi_1met'                , None                   ),
    ('hnl_dphi_2met'                , None                   ),
    ('hnl_pt_01'                    , None                   ),
    ('hnl_pt_02'                    , None                   ),
    ('hnl_pt_12'                    , 'sumPtl2l3'            , np.linspace(0.,100.,15 + 1)    ),
    ('hnl_pt_0met'                  , None                   ),
    ('hnl_pt_1met'                  , None                   ),
    ('hnl_pt_2met'                  , None                   ),
    ('hnl_dr_hn0'                   , None                   ),
    ('hnl_dr_hnvis0'                , None                   ),
    ('hnl_dr_hnvismet'              , None                   ),
    ('hnl_dphi_hn0'                 , None                   ),
    ('hnl_dphi_hnvis0'              , None                   ),
    ('hnl_dphi_hnvismet'            , None                   ),
    ('hnl_mt_0'                     , None                   ),
    ('hnl_mt_1'                     , None                   ),
    ('hnl_mt_2'                     , None                   ),
    ('hnl_mt_hnvis'                 , None                   ),
    ('l0_pt'                        , 'l1_pt'                , np.linspace(25.,100.,12 + 1)    ),
    ('l0_eta'                       , 'l1_eta'               , np.linspace(-2.5, 2.5, 10 + 1)  ),
    ('l0_phi'                       , 'l1_phi'               , np.linspace(-3.15, 3.15, 10 + 1)),
    ('l0_q'                         , 'l1_q'                 , np.linspace(-1, 2  ,3 + 1)      ),
    ('l0_mass'                      , None                   ),
    ('l0_pdgid'                     , 'l1_flav'              ),
    ('l0_jet_pt'                    , None                   ),
    ('l0_jet_eta'                   , None                   ),
    ('l0_jet_phi'                   , None                   ),
    ('l0_jet_q'                     , None                   ),
    ('l0_jet_mass'                  , None                   ),
    ('l0_jet_pdgid'                 , None                   ),
    ('l0_jet_mva_pu'                , None                   ),
    ('l0_jet_id_pu'                 , None                   ),
    ('l0_jet_flavour_parton'        , None                   ),
    ('l0_jet_csv'                   , None                   ),
    ('l0_jet_df'                    , None                   ),
    ('l0_jet_df_b'                  , None                   ),
    ('l0_jet_df_bb'                 , None                   ),
    ('l0_jet_df_lepb'               , None                   ),
    ('l0_jet_df_sf_flag'            , None                   ),
    ('l0_jet_genjet_pt'             , None                   ),
    ('l0_pte'                       , None                   ),
    ('l0_px'                        , None                   ),
    ('l0_py'                        , None                   ),
    ('l0_pz'                        , None                   ),
    ('l0_e'                         , 'l1_e'                 , np.linspace( 0. , 300,20 + 1)    ),
    ('l0_dxy'                       , 'l1_dxy'               , np.linspace(-0.3, 0.3,12 + 1)    ),
    ('l0_dxy_error'                 , None                   ),
    ('l0_dz'                        , 'l1_dz'                , np.linspace(-10, 10  ,20 + 1)    ),
    (None                           , 'l1_3dSip'             ),
    (None                           , 'l1_2dSip'             ),
    ('l0_dz_error'                  , None                   ),
    ('l0_weight'                    , None                   ),
    ('l0_weight_id'                 , None                   ),
    ('l0_weight_iso'                , None                   ),
    ('l0_weight_reco'               , None                   ),
    ('l0_weight_trigger'            , None                   ),
    ('l0_weight_idiso'              , None                   ),
    ('l0_weight_tracking'           , None                   ),
    ('l0_reliso_rho_04'             , None                   ),
    ('l0_reliso_rho_03'             , 'l1_relIso'            , np.linspace(0., 0.2  ,12 + 1)    ),
    ('l0_reliso_dB_05_04'           , None                   ),
    ('l0_reliso_dB_05_03'           , None                   ),
    ('l0_reliso_dB_02_04'           , None                   ),
    ('l0_reliso_dB_02_03'           , None                   ),
    ('l0_id_s'                      , None                   ),
    ('l0_id_l'                      , None                   ),
    ('l0_id_m'                      , None                   ),
    ('l0_id_hnl_m'                  , None                   ),
    ('l0_id_t'                      , None                   ),
    ('l0_id_tnv'                    , None                   ),
    ('l0_id_hpt'                    , None                   ),
    ('l0_is_sa'                     , None                   ),
    ('l0_is_gl'                     , None                   ),
    ('l0_is_tk'                     , None                   ),
    ('l0_is_pf'                     , None                   ),
    ('l0_is_oot'                    , None                   ),
    ('l0_simType'                   , None                   ),
    ('l0_simFlavour'                , None                   ),
    ('l0_simHeaviestMotherFlavour'  , None                   ),
    ('l0_simPdgId'                  , None                   ),
    ('l0_simMotherPdgId'            , None                   ),
    ('l0_simBX'                     , None                   ),
    ('l0_simProdRho'                , None                   ),
    ('l0_simProdZ'                  , None                   ),
    ('l0_simPt'                     , None                   ),
    ('l0_simEta'                    , None                   ),
    ('l0_simPhi'                    , None                   ),
    ('hlt_IsoMu22'                  , None                   ),
    ('hlt_IsoTkMu22'                , None                   ),
    ('hlt_IsoMu22_eta2p1'           , None                   ),
    ('hlt_IsoTkMu22_eta2p1'         , None                   ),
    ('hlt_IsoMu24'                  , '_HLT_IsoMu24'         , np.linspace(0., 2, 2 + 1) ),
    ('hlt_IsoTkMu24'                , '_HLT_IsoTkMu24'       , np.linspace(0., 2, 2 + 1) ),
    ('hlt_IsoMu27'                  , '_HLT_IsoMu27'         , np.linspace(0., 2, 2 + 1) ),
    ('hlt_IsoTkMu27'                , None                   ),
    ('hlt_Mu50'                     , None                   ),
    ('hlt_TkMu50'                   , None                   ),
    ('l1_pt'                        , 'l2_pt'                , np.linspace( 5., 50.,12 + 1)    ),
    ('l1_eta'                       , 'l2_eta'               , np.linspace(-2.5, 2.5, 10 + 1)  ),
    ('l1_phi'                       , 'l2_phi'               , np.linspace(-3.15, 3.15, 10 + 1)),
    ('l1_q'                         , 'l2_q'                 ),
    ('l1_mass'                      , None                   ),
    ('l1_pdgid'                     , 'l2_flav'              ),
    ('l1_jet_pt'                    , None                   ),
    ('l1_jet_eta'                   , None                   ),
    ('l1_jet_phi'                   , None                   ),
    ('l1_jet_q'                     , None                   ),
    ('l1_jet_mass'                  , None                   ),
    ('l1_jet_pdgid'                 , None                   ),
    ('l1_jet_mva_pu'                , None                   ),
    ('l1_jet_id_pu'                 , None                   ),
    ('l1_jet_flavour_parton'        , None                   ),
    ('l1_jet_csv'                   , None                   ),
    ('l1_jet_df'                    , None                   ),
    ('l1_jet_df_b'                  , None                   ),
    ('l1_jet_df_bb'                 , None                   ),
    ('l1_jet_df_lepb'               , None                   ),
    ('l1_jet_df_sf_flag'            , None                   ),
    ('l1_jet_genjet_pt'             , None                   ),
    ('l1_pte'                       , None                   ),
    ('l1_px'                        , None                   ),
    ('l1_py'                        , None                   ),
    ('l1_pz'                        , None                   ),
    ('l1_e'                         , 'l2_e'                 , np.linspace( 0. , 200,20 + 1)    ),
    ('l1_dxy'                       , 'l2_dxy'               , np.linspace(-0.3, 0.3,12 + 1)    ),
    ('l1_dxy_error'                 , None                   ),
    ('l1_dz'                        , 'l2_dz'                , np.linspace(-10, 10  ,20 + 1)    ),
    (None                           , 'l2_3dSip'             ),
    (None                           , 'l2_2dSip'             ),
    ('l1_dz_error'                  , None                   ),
    ('l1_weight'                    , None                   ),
    ('l1_weight_id'                 , None                   ),
    ('l1_weight_iso'                , None                   ),
    ('l1_weight_reco'               , None                   ),
    ('l1_weight_trigger'            , None                   ),
    ('l1_weight_idiso'              , None                   ),
    ('l1_weight_tracking'           , None                   ),
    ('l1_reliso_rho_04'             , None                   ),
    ('l1_reliso_rho_03'             , 'l2_relIso'            , np.linspace(0., 0.2  ,12 + 1)    ),
    ('l1_reliso_dB_05_04'           , None                   ),
    ('l1_reliso_dB_05_03'           , None                   ),
    ('l1_reliso_dB_02_04'           , None                   ),
    ('l1_reliso_dB_02_03'           , None                   ),
    ('l1_id_s'                      , None                   ),
    ('l1_id_l'                      , None                   ),
    ('l1_id_m'                      , None                   ),
    ('l1_id_hnl_m'                  , None                   ),
    ('l1_id_t'                      , None                   ),
    ('l1_id_tnv'                    , None                   ),
    ('l1_id_hpt'                    , None                   ),
    ('l1_is_sa'                     , None                   ),
    ('l1_is_gl'                     , None                   ),
    ('l1_is_tk'                     , None                   ),
    ('l1_is_pf'                     , None                   ),
    ('l1_is_oot'                    , None                   ),
    ('l1_simType'                   , None                   ),
    ('l1_simFlavour'                , None                   ),
    ('l1_simHeaviestMotherFlavour'  , None                   ),
    ('l1_simPdgId'                  , None                   ),
    ('l1_simMotherPdgId'            , None                   ),
    ('l1_simBX'                     , None                   ),
    ('l1_simProdRho'                , None                   ),
    ('l1_simProdZ'                  , None                   ),
    ('l1_simPt'                     , None                   ),
    ('l1_simEta'                    , None                   ),
    ('l1_simPhi'                    , None                   ),
    ('l2_pt'                        , 'l3_pt'                , np.linspace( 5., 30.,12 + 1)    ),
    ('l2_eta'                       , 'l3_eta'               , np.linspace(-2.5, 2.5, 10 + 1)  ),
    ('l2_phi'                       , 'l3_phi'               , np.linspace(-3.15, 3.15, 10 + 1)),
    ('l2_q'                         , 'l3_q'                 , np.linspace(-1, 2  ,3 + 1)      ),
    ('l2_mass'                      , None                   ),
    ('l2_pdgid'                     , 'l3_flav'              ),
    ('l2_jet_pt'                    , None                   ),
    ('l2_jet_eta'                   , None                   ),
    ('l2_jet_phi'                   , None                   ),
    ('l2_jet_q'                     , None                   ),
    ('l2_jet_mass'                  , None                   ),
    ('l2_jet_pdgid'                 , None                   ),
    ('l2_jet_mva_pu'                , None                   ),
    ('l2_jet_id_pu'                 , None                   ),
    ('l2_jet_flavour_parton'        , None                   ),
    ('l2_jet_csv'                   , None                   ),
    ('l2_jet_df'                    , None                   ),
    ('l2_jet_df_b'                  , None                   ),
    ('l2_jet_df_bb'                 , None                   ),
    ('l2_jet_df_lepb'               , None                   ),
    ('l2_jet_df_sf_flag'            , None                   ),
    ('l2_jet_genjet_pt'             , None                   ),
    ('l2_pte'                       , None                   ),
    ('l2_px'                        , None                   ),
    ('l2_py'                        , None                   ),
    ('l2_pz'                        , None                   ),
    ('l2_e'                         , 'l3_e'                 , np.linspace( 0. , 200,20 + 1)    ),
    ('l2_dxy'                       , 'l3_dxy'               , np.linspace(-0.3, 0.3,12 + 1)    ),
    ('l2_dxy_error'                 , None                   ),
    ('l2_dz'                        , 'l3_dz'                , np.linspace(-10, 10  ,20 + 1)    ),
    (None                           , 'l3_3dSip'             ),
    (None                           , 'l3_2dSip'             ),
    ('l2_dz_error'                  , None                   ),
    ('l2_weight'                    , None                   ),
    ('l2_weight_id'                 , None                   ),
    ('l2_weight_iso'                , None                   ),
    ('l2_weight_reco'               , None                   ),
    ('l2_weight_trigger'            , None                   ),
    ('l2_weight_idiso'              , None                   ),
    ('l2_weight_tracking'           , None                   ),
    ('l2_reliso_rho_04'             , None                   ),
    ('l2_reliso_rho_03'             , 'l3_relIso'            , np.linspace(0., 0.2  ,12 + 1)    ),
    ('l2_reliso_dB_05_04'           , None                   ),
    ('l2_reliso_dB_05_03'           , None                   ),
    ('l2_reliso_dB_02_04'           , None                   ),
    ('l2_reliso_dB_02_03'           , None                   ),
    ('l2_id_s'                      , None                   ),
    ('l2_id_l'                      , None                   ),
    ('l2_id_m'                      , None                   ),
    ('l2_id_hnl_m'                  , None                   ),
    ('l2_id_t'                      , None                   ),
    ('l2_id_tnv'                    , None                   ),
    ('l2_id_hpt'                    , None                   ),
    ('l2_is_sa'                     , None                   ),
    ('l2_is_gl'                     , None                   ),
    ('l2_is_tk'                     , None                   ),
    ('l2_is_pf'                     , None                   ),
    ('l2_is_oot'                    , None                   ),
    ('l2_simType'                   , None                   ),
    ('l2_simFlavour'                , None                   ),
    ('l2_simHeaviestMotherFlavour'  , None                   ),
    ('l2_simPdgId'                  , None                   ),
    ('l2_simMotherPdgId'            , None                   ),
    ('l2_simBX'                     , None                   ),
    ('l2_simProdRho'                , None                   ),
    ('l2_simProdZ'                  , None                   ),
    ('l2_simPt'                     , None                   ),
    ('l2_simEta'                    , None                   ),
    ('l2_simPhi'                    , None                   ),
    ('pv_x'                         , None                   ),
    ('pv_y'                         , None                   ),
    ('pv_z'                         , None                   ),
    ('pv_xe'                        , None                   ),
    ('pv_ye'                        , None                   ),
    ('pv_ze'                        , None                   ),
    ('bs_x'                         , None                   ),
    ('bs_y'                         , None                   ),
    ('bs_z'                         , None                   ),
    ('bs_sigma_x'                   , None                   ),
    ('bs_sigma_y'                   , None                   ),
    ('bs_sigma_z'                   , None                   ),
    ('bs_dxdz'                      , None                   ),
    ('bs_dydz'                      , None                   ),
    ('sv_covxx'                     , None                   ),
    ('sv_covyy'                     , None                   ),
    ('sv_covzz'                     , None                   ),
    ('sv_covxy'                     , None                   ),
    ('sv_covxz'                     , None                   ),
    ('sv_covyz'                     , None                   ),
    ('sv_chi2'                      , 'vertex_chi2'          , np.linspace(0., 20  ,20 + 1)    ),
    ('sv_dimension'                 , None                   ),
    ('sv_isValid'                   , None                   ),
    ('sv_nTracks'                   , None                   ),
    ('sv_ndof'                      , None                   ),
    ('sv_normalizedChi2'            , None                   ),
    ('sv_x'                         , 'vertex_x'             , np.linspace(-5., 5  ,20 + 1)      ),
    ('sv_y'                         , 'vertex_y'             , np.linspace(-5., 5  ,20 + 1)      ),
    ('sv_z'                         , 'vertex_z'             , np.linspace(-20.,20 ,20 + 1)      ),
    ('sv_xError'                    , 'vertexerr_x'          , np.linspace(  0.,0.4 ,20 + 1)     ),
    ('sv_yError'                    , 'vertexerr_y'          , np.linspace(  0.,0.4 ,20 + 1)     ),
    ('sv_zError'                    , 'vertexerr_z'          , np.linspace(  0.,0.4 ,20 + 1)     ),
    ('sv_prob'                      , 'vertex_prob'          , np.linspace( 0   ,   1   , 20 + 1)),
    ('sv_cos'                       , 'costheta'             , np.linspace( 0.9 ,   1   , 30 + 1)),
    ('pass_e_veto'                  , None                   ),
    ('pass_m_veto'                  , None                   ),
    ('hnl_2d_disp'                  , 'displ_2D'             , np.linspace( 0   ,  30   , 25 + 1)),
    ('hnl_3d_disp'                  , 'displ_3D'             , np.linspace( 0   ,  50   , 25 + 1)),
    ('hnl_2d_disp_sig'              , 'sign_displ_2D'        , np.linspace( 0   ,1000   , 25 + 1)),
    ('hnl_3d_disp_sig'              , None                   ),
    ('puppimet_pt'                  , None                   ),
    ('puppimet_phi'                 , None                   ),
    ('puppimet_cov00'               , None                   ),
    ('puppimet_cov01'               , None                   ),
    ('puppimet_cov11'               , None                   ),
    ('pfmet_pt'                     , '_met'                 , np.linspace( 0.,200 ,20 + 1)     ),
    ('pfmet_phi'                    , None                   ),
    ('pfmet_cov00'                  , None                   ),
    ('pfmet_cov01'                  , None                   ),
    ('pfmet_cov11'                  , None                   ),
    ('pass_met_filters'             , None                   ),
    ('j1_pt'                        , None                   ),
    ('j1_eta'                       , None                   ),
    ('j1_phi'                       , None                   ),
    ('j1_q'                         , None                   ),
    ('j1_mass'                      , None                   ),
    ('j1_pdgid'                     , None                   ),
    ('j1_mva_pu'                    , None                   ),
    ('j1_id_pu'                     , None                   ),
    ('j1_flavour_parton'            , None                   ),
    ('j1_csv'                       , None                   ),
    ('j1_df'                        , None                   ),
    ('j1_df_b'                      , None                   ),
    ('j1_df_bb'                     , None                   ),
    ('j1_df_lepb'                   , None                   ),
    ('j1_df_sf_flag'                , None                   ),
    ('j1_genjet_pt'                 , None                   ),
    ('j2_pt'                        , None                   ),
    ('j2_eta'                       , None                   ),
    ('j2_phi'                       , None                   ),
    ('j2_q'                         , None                   ),
    ('j2_mass'                      , None                   ),
    ('j2_pdgid'                     , None                   ),
    ('j2_mva_pu'                    , None                   ),
    ('j2_id_pu'                     , None                   ),
    ('j2_flavour_parton'            , None                   ),
    ('j2_csv'                       , None                   ),
    ('j2_df'                        , None                   ),
    ('j2_df_b'                      , None                   ),
    ('j2_df_bb'                     , None                   ),
    ('j2_df_lepb'                   , None                   ),
    ('j2_df_sf_flag'                , None                   ),
    ('j2_genjet_pt'                 , None                   ),
    ('bj1_pt'                       , None                   ),
    ('bj1_eta'                      , None                   ),
    ('bj1_phi'                      , None                   ),
    ('bj1_q'                        , None                   ),
    ('bj1_mass'                     , None                   ),
    ('bj1_pdgid'                    , None                   ),
    ('bj1_mva_pu'                   , None                   ),
    ('bj1_id_pu'                    , None                   ),
    ('bj1_flavour_parton'           , None                   ),
    ('bj1_csv'                      , None                   ),
    ('bj1_df'                       , None                   ),
    ('bj1_df_b'                     , None                   ),
    ('bj1_df_bb'                    , None                   ),
    ('bj1_df_lepb'                  , None                   ),
    ('bj1_df_sf_flag'               , None                   ),
    ('bj1_genjet_pt'                , None                   ),
    ('bj2_pt'                       , None                   ),
    ('bj2_eta'                      , None                   ),
    ('bj2_phi'                      , None                   ),
    ('bj2_q'                        , None                   ),
    ('bj2_mass'                     , None                   ),
    ('bj2_pdgid'                    , None                   ),
    ('bj2_mva_pu'                   , None                   ),
    ('bj2_id_pu'                    , None                   ),
    ('bj2_flavour_parton'           , None                   ),
    ('bj2_csv'                      , None                   ),
    ('bj2_df'                       , None                   ),
    ('bj2_df_b'                     , None                   ),
    ('bj2_df_bb'                    , None                   ),
    ('bj2_df_lepb'                  , None                   ),
    ('bj2_df_sf_flag'               , None                   ),
    ('bj2_genjet_pt'                , None                   ),
    ('nj'                           , None                   ),
    ('nj30'                         , None                   ),
    ('nbj'                          , None                   ),
    ('lhe_weight'                   , None                   ),
    ('pass_mmm'                     , None                   ),
    ('pass_mem'                     , None                   ),
    ('pass_eee'                     , None                   ),
    ('pass_eem'                     , None                   ),
    ('channel'                      , None                   ),
    ('abs_l0_eta'                   , None                   ),
    ('abs_l1_eta'                   , None                   ),
    ('abs_l2_eta'                   , None                   ),
    ('abs_l0_pdgid'                 , None                   ),
    ('abs_l1_pdgid'                 , None                   ),
    ('abs_l2_pdgid'                 , None                   ),
    ('log_abs_l0_dxy'               , None                   ),
    ('log_abs_l0_dz'                , None                   ),
    ('log_abs_l1_dxy'               , None                   ),
    ('log_abs_l1_dz'                , None                   ),
    ('log_abs_l2_dxy'               , None                   ),
    ('log_abs_l2_dz'                , None                   ),
    ('abs_q_02'                     , None                   ),
    ('abs_q_01'                     , None                   ),
    ('abs_q_12'                     , None                   ),
    ('log_l0_dxy_sig'               , None                   ),
    ('log_l1_dxy_sig'               , None                   ),
    ('log_l2_dxy_sig'               , None                   ),
    ('log_l0_dz_sig'                , None                   ),
    ('log_l1_dz_sig'                , None                   ),
    ('log_l2_dz_sig'                , None                   ),
    ('log_hnl_2d_disp'              , None                   ),
    ('log_hnl_2d_disp_sig'          , None                   ),
    ('l0_ptcone'                    , None                   ),
    ('l1_ptcone'                    , None                   ),
    ('l2_ptcone'                    , None                   ),
    ('hnl_2d_disp_sig_alt'          , 'sign_displ_2D'        , np.linspace( 0   ,1000   , 25 + 1)),
    ('_norm_'                       , None                   ),
    ('year'                         , None                   ),
    ('isdata'                       , None                   ),
    ('fr'                           , None                   ),
    ('fr_corr'                      , None                   ),
    ('__index__'                    , None                   ),
    ('min_dphi_0_12'                , 'minDeltaPhi'          , np.linspace( 0., 3.15, 10 + 1)),
]

# Name: w_lxh Title: w_lxh/D
# Name: w_totSF Title: w_totSF/D
# Name: w_promptSF Title: w_promptSF/D
# Name: w_displacedSF Title: w_displacedSF/D
# Name: w_pileupSF Title: w_pileupSF/D
